# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Helper function to source files if they exist
function so {
	[ -s $1 ] && source $1;
}

# Enable HomeBrew
if [ -d /opt/homebrew/bin/ ]; then
	export PATH="/opt/homebrew/bin:$PATH"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	. /etc/bash_completion
elif [ -f /usr/local/etc/bash_completion ] && ! shopt -oq posix; then
	. /usr/local/etc/bash_completion
else
	if [ -f /usr/share/git/completion/git-prompt.sh ]; then
		. /usr/share/git/completion/git-prompt.sh
	fi
	if [ -f /usr/share/git/completion/git-completion.bash ]; then
		. /usr/share/git/completion/git-completion.bash
	fi
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Explicitly set XDG variables
if [ -z ${XDG_CONFIG_HOME+x} ]; then
	export XDG_CONFIG_HOME=$HOME/.config
fi
if [ -z ${XDG_CACHE_HOME+x} ]; then
	export XDG_CACHE_HOME=$HOME/.cache
fi
if [ -z ${XDG_DATA_HOME+x} ]; then
	export XDG_DATA_HOME=$HOME/.local/share
fi
if [ -z ${XDG_RUNTIME_DIR+x} ]; then
	if [ x$(uname) == 'xDarwin' ]; then
		export XDG_RUNTIME_DIR=$TMPDIR
	else
		# TODO: What to do on not-Darwin? XDG_RUNTIME_DIR has special
		#       requirements that are difficult to fulfill (e.g. only lasting
		#       from first login to last logout).  But then systemd should be
		#       setting a suitable value.
		:
	fi
fi

so ${XDG_CONFIG_HOME}/bash/export.bash
gpgconf --launch gpg-agent
so ${XDG_CONFIG_HOME}/bash/shopt.bash
so ${XDG_CONFIG_HOME}/bash/colours.bash
# Apply base16 colour config if there is an existing config file
if [ -f "$BASE16_CONFIG" ]; then
	colour
fi
so ${XDG_CONFIG_HOME}/bash/funcs.bash
#so ${XDG_CONFIG_HOME}/bash/prompt.bash
so ${XDG_CONFIG_HOME}/bash/alias.bash

eval "$(${HOME}/bin/starship init bash)"
