if v:progname == 'vi'
	set noloadplugins
endif

let mapleader="\<Space>"
let maplocalleader="\\"

" Extension -> filetype mappings.
let filetype_m='objc'
let filetype_pl='prolog'

if has('gui')
  " Turn off scrollbars. (Default on macOS is "egmrL").
  set guioptions-=L
  set guioptions-=R
  set guioptions-=b
  set guioptions-=l
  set guioptions-=r
endif

" Improve responsiveness for async plugins, the default is 4000ms
set updatetime=100

" Allow local additions
let s:vimrc_local=$XDG_CONFIG_DIR . '/vim/vimrc.local'
if filereadable(s:vimrc_local)
	execute 'source ' . s:vimrc_local
endif

" put netrwhist into XDG directory instead of the first directory in the runtime
" path
let g:netrw_home=$XDG_DATA_HOME . '/vim'

if &loadplugins
	if has('packages')
		packadd! base16-vim

		packadd! deoplete-lsp
		packadd! rust.vim

		if has('nvim')
			packadd! nvim-lsp
			lua require'nvim_lsp'.pyls.setup{}
			lua require'nvim_lsp'.rust_analyzer.setup({})
		endif

		let g:signify_sign_show_count        = 0
		packadd! vim-signify

	endif
endif

" After this file is sourced, plugin code will be evaluated.
" Automatic, language-dependent indentation, syntax coloring and other
" functionality.
"
" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype indent plugin on
syntax on

" See ~/.vim/after for files evaluated after that.
" See `:scriptnames` for a list of all scripts, in evaluation order.
" Launch Vim with `vim --startuptime vim.log` for profiling info.
"
" To see all leader mappings, including those from plugins:
"
"   vim -c 'set t_te=' -c 'set t_ti=' -c 'map <space>' -c q | sort
